K:\cocos_pristine\cocos_2d_new\docgen\api\cocos.audio.SDL.darwin.txt:4: WARNING: autodoc: failed to import module 'cocos.audio.SDL.darwin'; the following exception was raised:
Traceback (most recent call last):
  File "c:\python35-64\lib\site-packages\sphinx\ext\autodoc.py", line 507, in import_object
    __import__(self.modname)
  File "K:\cocos_pristine\cocos_2d_new\cocos\audio\SDL\darwin.py", line 18, in <module>
    from Foundation import *
ImportError: No module named 'Foundation'
K:\cocos_pristine\cocos_2d_new\docgen\api\cocos.audio.SDL.sound.txt:4: WARNING: autodoc: failed to import module 'cocos.audio.SDL.sound'; the following exception was raised:
Traceback (most recent call last):
  File "K:\cocos_pristine\cocos_2d_new\cocos\audio\SDL\dll.py", line 60, in __init__
    self._load_library_win()
  File "K:\cocos_pristine\cocos_2d_new\cocos\audio\SDL\dll.py", line 92, in _load_library_win
    self._dll = getattr(cdll, self.library_name)
  File "c:\python35-64\lib\ctypes\__init__.py", line 417, in __getattr__
    dll = self._dlltype(name)
  File "c:\python35-64\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] No se puede encontrar el módulo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35-64\lib\site-packages\sphinx\ext\autodoc.py", line 507, in import_object
    __import__(self.modname)
  File "K:\cocos_pristine\cocos_2d_new\cocos\audio\SDL\sound.py", line 47, in <module>
    _dll = SDL.dll.SDL_DLL('SDL_sound', None, '1.2')
  File "K:\cocos_pristine\cocos_2d_new\cocos\audio\SDL\dll.py", line 63, in __init__
    library_name))
ImportError: Dynamic library "SDL_sound" was not found
K:\cocos_pristine\cocos_2d_new\docgen\api\modules.txt:: WARNING: document isn't included in any toctree
WARNING: html_static_path entry 'K:\\cocos_pristine\\cocos_2d_new\\docgen\\_static' does not exist
